# Generated by Django 4.2.1 on 2023-05-22 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='image',
            field=models.ImageField(blank=True, help_text='image size 86 X 86', upload_to='image/menu/ProductCategory'),
        ),
    ]
